[0m21:30:23.442106 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107053a30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1080aabe0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1080aa190>]}


============================== 21:30:23.444296 | ab0635ca-85f3-46b1-900c-f0b26ca2ce4e ==============================
[0m21:30:23.444296 [info ] [MainThread]: Running with dbt=1.10.3
[0m21:30:23.444560 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/Users/clintgilmore/.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt init analytics_project', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:30:23.452370 [debug] [MainThread]: Starter project path: /Users/clintgilmore/Desktop/Analytics/.venv/lib/python3.9/site-packages/dbt/include/starter_project
[0m21:30:23.456446 [info ] [MainThread]: 
Your new dbt project "analytics_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m21:30:23.456679 [info ] [MainThread]: Setting up your profile.
[0m21:30:28.103677 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 4.7001915, "process_in_blocks": "0", "process_kernel_time": 0.094628, "process_mem_max_rss": "103268352", "process_out_blocks": "0", "process_user_time": 0.566453}
[0m21:30:28.104091 [debug] [MainThread]: Command `dbt init` succeeded at 21:30:28.104035 after 4.70 seconds
[0m21:30:28.104293 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107053a30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108034220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107ee1c70>]}
[0m21:30:28.104506 [debug] [MainThread]: Flushing usage events
[0m21:30:29.181991 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:41:58.593805 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107c76a30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1116c3310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1116c3dc0>]}


============================== 22:41:58.595400 | 07197c90-3fe3-4f0d-aa0d-0f3ea4a71e56 ==============================
[0m22:41:58.595400 [info ] [MainThread]: Running with dbt=1.10.3
[0m22:41:58.595657 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/clintgilmore/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt run -s test', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:41:58.595968 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/clintgilmore/Desktop/Analytics/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:41:58.596606 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.036844168, "process_in_blocks": "0", "process_kernel_time": 0.066067, "process_mem_max_rss": "96436224", "process_out_blocks": "0", "process_user_time": 0.519324}
[0m22:41:58.596793 [debug] [MainThread]: Command `dbt run` failed at 22:41:58.596751 after 0.04 seconds
[0m22:41:58.596941 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107c76a30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1116c3b50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1116c3250>]}
[0m22:41:58.597087 [debug] [MainThread]: Flushing usage events
[0m22:41:59.931092 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:25:28.286423 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1079efa00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108a3a160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108a3ab20>]}


============================== 17:25:28.288483 | 01d64535-07d3-40e3-abb5-e37e32348797 ==============================
[0m17:25:28.288483 [info ] [MainThread]: Running with dbt=1.10.3
[0m17:25:28.288756 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/clintgilmore/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt build', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:25:28.289080 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/clintgilmore/Desktop/Analytics/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:25:28.290137 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.0412585, "process_in_blocks": "0", "process_kernel_time": 0.099471, "process_mem_max_rss": "97222656", "process_out_blocks": "0", "process_user_time": 0.531306}
[0m17:25:28.290325 [debug] [MainThread]: Command `dbt build` failed at 17:25:28.290282 after 0.04 seconds
[0m17:25:28.290480 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1079efa00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108a151c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107d14160>]}
[0m17:25:28.290625 [debug] [MainThread]: Flushing usage events
[0m17:25:29.363372 [debug] [MainThread]: An error was encountered while trying to flush usage events
